MaspTeachingWebmvc/EduExamine/Controllers/ClassesController.cs
using EduExamine.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EduExamine.Controllers
{
    public class ClassesController : Controller
    {
        EduExamineContext _db;
        public HttpCookie userCookie;
        public AdminType AdminType;
        public int? GetEduYearId;

        public ClassesController()
        {
            _db = new EduExamineContext();
        }

        public bool LoginStatus()
        {
            if (Request.Cookies["MapsUser"] != null)
            {
                userCookie = HttpContext.Request.Cookies["MapsUser"];
                AdminType = (AdminType)Enum.Parse(typeof(AdminType), userCookie["Type"], true);
                GetEduYearId = Convert.ToInt32(userCookie["EduYearId"]);
                return true;
            }
            return false;
        }


        public ActionResult CIndex(int? page)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            var model = _db.Classess.OrderBy(o => o.ClassName).ToList();
            return View(model.ToPagedList(page ?? 1, 20));
        }

        public ActionResult Create()
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClassName")] Classes model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            bool Exists = _db.Classess.Any(d => d.ClassName.Equals(model.ClassName));
            if (!Exists)
            {
                if (ModelState.IsValid)
                {
                    _db.Classess.Add(model);
                    _db.SaveChanges();
                    return Json("");
                }
                else
                {
                    return Json("Model is not valid.");
                }
            }
            else
            {
                return Json("Try another label name");
            }
        }

        public ActionResult Edit(long? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Classes classes = _db.Classess.Find(id);
            if (classes == null)
            {
                return HttpNotFound();
            }
            return View(classes);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClassesId,ClassName")] Classes model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            bool Exists = _db.Classess.Any(d => d.ClassName.Equals(model.ClassName));
            if (!Exists)
            {

                if (ModelState.IsValid)
                {
                    _db.Entry(model).State = EntityState.Modified;
                    _db.SaveChanges();
                    return Json("");
                }
                else
                {
                    return Json("Model is not valid.");
                }
            }
            else
            {
                return Json("Try another label name");
            }
        }

        public ActionResult Delete(long? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Classes classes = _db.Classess.Find(id);
            if (classes == null)
            {
                return HttpNotFound();
            }
            return View(classes);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            Classes classes = _db.Classess.Find(id);
            _db.Classess.Remove(classes);
            _db.SaveChanges();
            return Json("");
        }

        //Subject Control of class

        public ActionResult SubjectDisplay(int? page, int? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = _db.Subjects.Include(d => d.Classes).Where(d => d.ClassesId == id).OrderBy(d => d.SubjectName);
            if (model.Count() == 0)
            {
                List<Subject> subList = new List<Subject>();
                subList.Add(new Subject() { Classes = _db.Classess.Find(id) });
                return View(subList.ToPagedList(page ?? 1, 20));
            }
            return View(model.ToPagedList(page ?? 1, 20));
        }

        public ActionResult SubjectCreate(int? ClassesId)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);
            Classes classes = _db.Classess.Find(ClassesId);
            Subject subject = new Subject() { ClassesId = classes.ClassesId, Classes = classes };

            return View(subject);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubjectCreate([Bind(Include = "SubjectName,ClassesId")] Subject model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            bool Exists = _db.Subjects.Any(d => d.SubjectName.Equals(model.SubjectName) && d.ClassesId.Equals(model.ClassesId));
            if (!Exists)
            {
                if (ModelState.IsValid)
                {
                    _db.Subjects.Add(model);
                    _db.SaveChanges();
                    return Json("");
                }
                else
                {
                    return Json("Model is not valid.");
                }
            }
            else
            {
                return Json("Try another label name");
            }
        }

        public ActionResult SubjectEdit(long? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = _db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubjectEdit([Bind(Include = "SubjectId,SubjectName,ClassesId")] Subject model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            bool Exists = _db.Subjects.Any(d => d.SubjectName.Equals(model.SubjectName) && d.ClassesId.Equals(model.ClassesId));
            if (!Exists)
            {
                if (ModelState.IsValid)
                {
                    _db.Entry(model).State = EntityState.Modified;
                    _db.SaveChanges();
                    return Json("");
                }
                else
                {
                    return Json("Model is not valid.");
                }
            }
            else
            {
                return Json("Try another label name");
            }
        }

        public ActionResult SubjectDelete(long? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = _db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        [HttpPost, ActionName("SubjectDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult SubjectDeleteConfirmed([Bind(Include = "SubjectId")] Subject model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            Subject subject = _db.Subjects.Find(model.SubjectId);
            if (subject != null)
            {
                _db.Subjects.Remove(subject);
                _db.SaveChanges();
                return Json("");
            }
            else
            {
                return Json("No record found.");
            }

        }

        //Chapter Control of subject

        public ActionResult ChapterDisplay(int? page, int? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = _db.Chapters.Include(d => d.Subject).Include(d => d.Subject.Classes).Where(d => d.SubjectId == id && d.EduYearId == (int)GetEduYearId).OrderBy(d => d.ChapterId);
            if (model.Count() == 0)
            {
                List<Chapter> chapList = new List<Chapter>();
                Subject subject = _db.Subjects.Include(d => d.Classes).First(d => d.SubjectId == id);
                chapList.Add(new Chapter() { Subject = subject });
                return View(chapList.ToPagedList(page ?? 1, 20));
            }
            return View(model.ToPagedList(page ?? 1, 20));
        }

MaspTeachingWebmvc/EduExamine/Views/Classes/ChapterCreate.cshtml
@model EduExamine.Models.Chapter

@{
    ViewBag.Title = "Add New";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}
<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Add Chapter</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @using (Ajax.BeginForm("ChapterCreate", new AjaxOptions { }))
            {
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">
                    </div>
                </div>
                @Html.AntiForgeryToken()
                @Html.HiddenFor(d => d.SubjectId)
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
                    @Html.EditorFor(model => model.ChapterName, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER NO. OF CHAPTER YOU WANT TO CREATE" } })
                    @Html.ValidationMessageFor(model => model.ChapterName, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group text-right">
                    <input id="submit" type="button" value="Save" onclick="submitUniversal(this, '@Url.Action("ChapterDisplay", "Classes", new { id = Model.SubjectId })')" class="btn btn-info" />
                    <a href="@Url.Action("ChapterDisplay", "Classes", new { id = Model.SubjectId })" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Classes/ChapterDelete.cshtml
@model EduExamine.Models.Chapter

@{
    ViewBag.Title = "Edit " + Model.ChapterName;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}
<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Delete Chapter</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @using (Ajax.BeginForm("ChapterDelete", new AjaxOptions { }))
            {
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">
                    </div>
                </div>
                @Html.AntiForgeryToken()
                @Html.HiddenFor(d => d.SubjectId)
                @Html.HiddenFor(d => d.ChapterId)
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
                    @Html.EditorFor(model => model.ChapterName, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER NO. OF CHAPTER YOU WANT TO CREATE" } })
                    @Html.ValidationMessageFor(model => model.ChapterName, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group text-right">
                    <input id="submit" type="button" value="Delete" onclick="submitUniversal(this, '@Url.Action("ChapterDisplay", "Classes", new { id = Model.SubjectId })')" class="btn btn-danger" />
                    <a href="@Url.Action("ChapterDisplay", "Classes", new { id = Model.SubjectId })" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Classes/ChapterDisplay.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<EduExamine.Models.Chapter>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}
<div class="container-start">
    <div class="row">
        <div class="col-md-12 top_head">
            <a href="@Url.Action("CIndex", "Classes", null)" class="lnk lnk-default">
                @Model.First().Subject.Classes.ClassName
            </a>
            <span class="glyphicon glyphicon-menu-right small"></span>
            <a href="@Url.Action("SubjectDisplay", "Classes", new { id = Model.First().Subject.ClassesId })" class="lnk lnk-default">
                @Model.First().Subject.SubjectName
            </a>
            <span class="glyphicon glyphicon-menu-right small"></span>
            Chapters
        </div>
        <div class="col-md-12 text-left">
            <h5>
                @Html.ActionLink("+ Add New", "ChapterCreate", new { SubjectId = @Model.First().Subject.SubjectId })
            </h5>
        </div>

        <div class="col-md-12">
            @if (Model.First().ChapterName != null)
            {
                foreach (var item in Model)
                {
                    <div class="col-lg-2 newBox" title="@item.ChapterName">
                        <div class="row head">
                            @item.ChapterName
                        </div>
                        <div class="row control">
                            <div class="col-md-4 btntext">
                                @Html.ActionLink("Settings", "SettingsDisplay", new { id = item.ChapterId })
                            </div>
                            <div class="col-md-4 btntext">
                                @Html.ActionLink("Edit", "ChapterEdit", new { id = item.ChapterId })
                            </div>
                            <div class="col-md-4 btntext">
                                @Html.ActionLink("Delete", "ChapterDelete", new { id = item.ChapterId })
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                    <div class="col-lg-12 newBox" title="No records">
                        <div class="row head" style="height:250px;">
                            No chapters added to @Model.First().Subject.SubjectName. <br />
                            <br />
                            <p style="font-size:11px;">
                                Click on add link to add number of chapters
                            </p>
                        </div>
                        <div class="row control">

                        </div>
                    </div>
            }
        </div>
        <div class="col-md-12 text-center top-twenty">
            @Html.PagedListPager(Model, page => Url.Action("ChapterDisplay", new { page }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Classes/ChapterEdit.cshtml
@model EduExamine.Models.Chapter

@{
    ViewBag.Title = "Edit "+ Model.ChapterName;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}
<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Edit Chapter</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @using (Ajax.BeginForm("ChapterEdit", new AjaxOptions { }))
            {
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">
                    </div>
                </div>
                @Html.AntiForgeryToken()
                @Html.HiddenFor(d => d.SubjectId)
                @Html.HiddenFor(d => d.ChapterId)
                @Html.HiddenFor(d => d.EduYearId)
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
                    @Html.EditorFor(model => model.ChapterName, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER NO. OF CHAPTER YOU WANT TO CREATE" } })
                    @Html.ValidationMessageFor(model => model.ChapterName, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group text-right">
                    <input id="submit" type="button" value="Edit" onclick="submitUniversal(this, '@Url.Action("ChapterDisplay", "Classes", new { id = Model.SubjectId })')" class="btn btn-success" />
                    <a href="@Url.Action("ChapterDisplay", "Classes", new { id = Model.SubjectId })" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Classes/Create.cshtml
@model EduExamine.Models.Classes

@{
    ViewBag.Title = "Add New";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}

<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Add Class</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @using (Ajax.BeginForm("Create", new AjaxOptions { }))
            {
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>

                @Html.AntiForgeryToken()

                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
                    @Html.EditorFor(model => model.ClassName, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER CLASS NAME" } })
                    @Html.ValidationMessageFor(model => model.ClassName, "", new { @class = "text-danger form-control-feedback" })
                </div>
               
                <div class="form-group text-right">
                    <input id="submit" type="button" value="Save" onclick="submitUniversal(this, '@Url.Action("CIndex", "Classes", null)')" class="btn btn-info" />
                    <a href="@Url.Action("CIndex", "Classes", null)" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Classes/Delete.cshtml
@model EduExamine.Models.Classes

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}

<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Delete Class</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @using (Ajax.BeginForm("Delete", new AjaxOptions { }))
            {
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>
                <p>Are you sure want to delete?</p>
                @Html.AntiForgeryToken()
                @Html.HiddenFor(d => d.ClassesId)
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
                    @Html.EditorFor(model => model.ClassName, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER CLASS NAME" } })
                    @Html.ValidationMessageFor(model => model.ClassName, "", new { @class = "text-danger form-control-feedback" })
                </div>

                <div class="form-group text-right">
                    <input id="submit" type="button" value="Delete" onclick="submitUniversal(this, '@Url.Action("CIndex", "Classes", null)')" class="btn btn-danger" />
                    <a href="@Url.Action("CIndex", "Classes", null)" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Classes/Details.cshtml
@model EduExamine.Models.Classes

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Classes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClassName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ClassesId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MaspTeachingWebmvc/EduExamine/Views/Classes/Edit.cshtml
@model EduExamine.Models.Classes

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}

<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Edit Class</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @using (Ajax.BeginForm("Edit", new AjaxOptions { }))
            {
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>

                @Html.AntiForgeryToken()
                @Html.HiddenFor(d => d.ClassesId)
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
                    @Html.EditorFor(model => model.ClassName, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER CLASS NAME" } })
                    @Html.ValidationMessageFor(model => model.ClassName, "", new { @class = "text-danger form-control-feedback" })
                </div>

                <div class="form-group text-right">
                    <input id="submit" type="button" value="Edit" onclick="submitUniversal(this, '@Url.Action("CIndex", "Classes", null)')" class="btn btn-success" />
                    <a href="@Url.Action("CIndex", "Classes", null)" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Classes/SubjectCreate.cshtml
@model EduExamine.Models.Subject

@{
    ViewBag.Title = "Add New";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}

<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Add Subject</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @using (Ajax.BeginForm("SubjectCreate", new AjaxOptions { }))
            {
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>

                @Html.AntiForgeryToken()
                @Html.HiddenFor(d => d.ClassesId)
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
                    @Html.EditorFor(model => model.SubjectName, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER SUBJECT NAME" } })
                    @Html.ValidationMessageFor(model => model.SubjectName, "", new { @class = "text-danger form-control-feedback" })
                </div>

                <div class="form-group text-right">
                    <input id="submit" type="button" value="Save" onclick="submitUniversal(this, '@Url.Action("SubjectDisplay", "Classes", new { id = Model.ClassesId })')" class="btn btn-info" />
                    <a href="@Url.Action("SubjectDisplay", "Classes", new { id = Model.ClassesId })" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Classes/SubjectDelete.cshtml
@model EduExamine.Models.Subject

@{
    ViewBag.Title = "Delete " + Model.SubjectName ;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}

<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Delete Subject</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @using (Ajax.BeginForm("SubjectDelete", new AjaxOptions { }))
            {
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>

                @Html.AntiForgeryToken()
                @Html.HiddenFor(d => d.ClassesId)
                @Html.HiddenFor(d =>d.SubjectId)
                <p>Are you sure want to remove?</p>
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
                    @Html.EditorFor(model => model.SubjectName, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER SUBJECT NAME" } })
                    @Html.ValidationMessageFor(model => model.SubjectName, "", new { @class = "text-danger form-control-feedback" })
                </div>

                <div class="form-group text-right">
                    <input id="submit" type="button" value="Delete" onclick="submitUniversal(this, '@Url.Action("SubjectDisplay", "Classes", new { id = Model.ClassesId })')" class="btn btn-danger" />
                    <a href="@Url.Action("SubjectDisplay", "Classes", new { id = Model.ClassesId })" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Classes/SubjectDisplay.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<EduExamine.Models.Subject>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}
<div class="container-start">
    <div class="row">
        <div class="col-md-12 top_head">
            <a href="@Url.Action("CIndex", "Classes", null)" class="lnk lnk-default">
                @Model.First().Classes.ClassName
            </a>
            <span class="glyphicon glyphicon-menu-right small"></span>
            Subjects
        </div>
        <div class="col-md-12 text-left">
            <h5>
                @Html.ActionLink("+ Add New", "SubjectCreate", new { ClassesId = @Model.First().Classes.ClassesId })
            </h5>
        </div>

        <div class="col-md-12">
            @if(Model.First().SubjectName!=null)
            { 
            foreach (var item in Model)
            {
                <div class="col-lg-2 newBox" title="@item.SubjectName">
                    <div class="row head">
                        @item.SubjectName
                    </div>
                    <div class="row control">
                        <div class="col-md-4 btntext">
                            @Html.ActionLink("Chapters", "ChapterDisplay", new { id = item.SubjectId, ClassesId = item.ClassesId })
                        </div>
                        <div class="col-md-4 btntext">
                            @Html.ActionLink("Edit", "SubjectEdit", new { id = item.SubjectId})
                        </div>
                        <div class="col-md-4 btntext">
                            @Html.ActionLink("Delete", "SubjectDelete", new { id = item.SubjectId})
                        </div>
                    </div>
                </div>
            }
            }
            else
            {
                    <div class="col-lg-12 newBox" title="No records">
                        <div class="row head" style="height:250px;">
                            No subjects added to @Model.First().Classes.ClassName. <br />
                            <br />
                            <p style="font-size:11px;">
                                Click on add link to add new subject
                            </p>
                        </div>
                        <div class="row control">

                        </div>
                    </div>
            }
        </div>
        <div class="col-md-12 text-center top-twenty">
            @Html.PagedListPager(Model, page => Url.Action("SubjectDisplay", new { page }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })
        </div>
    </div>
</div>