MaspTeachingWebmvc/EduExamine/Controllers/TeachersController.cs
using EduExamine.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EduExamine.Controllers
{
    public class TeachersController : Controller
    {
        EduExamineContext _db;
        public HttpCookie userCookie;
        public AdminType AdminType;
        public int? GetEduYearId;

        public TeachersController()
        {
            _db = new EduExamineContext();
        }

        public bool LoginStatus()
        {
            if (Request.Cookies["MapsUser"] != null)
            {
                userCookie = HttpContext.Request.Cookies["MapsUser"];
                AdminType = (AdminType)Enum.Parse(typeof(AdminType), userCookie["Type"], true);
                GetEduYearId = Convert.ToInt32(userCookie["EduYearId"]);
                return true;
            }
            return false;
        }

        [HttpGet]
        public ActionResult TIndex(int? page)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            var model = _db.Teachers.Include(d => d.TeacherSubjects).Where(d => d.Types == TeacherType.Teacher && d.EduYearId == GetEduYearId).ToList();
            if (model.Count == 0)
            {
                Teacher item = new Teacher() { Types = TeacherType.Teacher, TeacherId = 0, FullName = "" };
                List<Teacher> teacher = new List<Teacher>();
                teacher.Add(item);
                return View(teacher.ToPagedList(page ?? 1, 10));
            }
            return View(model.ToPagedList(page ?? 1, 10));

        }

        [HttpGet]
        public ActionResult Create()
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            Teacher teacher = new Teacher() { Types = TeacherType.Teacher, TeacherId = 0, FullName = "" };
            ViewBag.EduYearId = new SelectList(_db.EduYears, "EduYearId", "EduYearName");
            return View(teacher);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FullName,LoginName,Password,Types")] Teacher model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            bool Exists = _db.Teachers.Any(d => d.LoginName.Equals(model.LoginName));
            if (!Exists)
            {
                if (ModelState.IsValid)
                {
                    model.EduYear = _db.EduYears.Find((int)GetEduYearId);
                    model.EduYearId = (int)GetEduYearId;
                    _db.Teachers.Add(model);
                    _db.SaveChanges();
                    return Json("");
                }
                else
                {
                    return Json("Model is not valid.");
                }
            }
            else
            {
                return Json("Try another label name");
            }
        }

        [HttpGet]
        public ActionResult Edit(long? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Teacher model = _db.Teachers.Find(id);

            if (model == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TeacherId,FullName,LoginName,Password,Types,EduYearId")] Teacher model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (ModelState.IsValid)
            {
                model.EduYear = _db.EduYears.Find((int)GetEduYearId);
                model.EduYearId = (int)GetEduYearId;
                _db.Entry(model).State = EntityState.Modified;
                _db.SaveChanges();
                return Json("");
            }
            return View(model);
        }

        public ActionResult Delete(long? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teacher model = _db.Teachers.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePConfirmed(long? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            Teacher admin = _db.Teachers.Find(id);
            _db.Teachers.Remove(admin);
            _db.SaveChanges();
            return Json("");
        }

        //Subject list of teacher
        public ActionResult SubjectDisplay(int? page, long? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = _db.TeacherSubjects.Include(d => d.Subject).Include(d => d.Subject.Classes).Include(d => d.Teacher).Where(d => d.TeacherId == id).OrderBy(d => d.Subject.SubjectName);
            if (model.Count() == 0)
            {
                List<TeacherSubject> subList = new List<TeacherSubject>();
                subList.Add(new TeacherSubject() { Teacher = _db.Teachers.Find(id) });
                return View(subList.ToPagedList(page ?? 1, 20));
            }
            return View(model.ToPagedList(page ?? 1, 20));
        }

        public ActionResult SubjectCreate(long? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            Teacher teacher = _db.Teachers.Find(id);

            List<SubjectList> lstSubject = new List<SubjectList>();

            var subjects = _db.Subjects.Include(d => d.Classes).ToList();

            foreach (var item in subjects)
            {
                SubjectList subject = new SubjectList()
                {
                    SubjectId = item.SubjectId,
                    SubjectName = item.SubjectName,
                    ClassName = item.Classes.ClassName,
                    Status = false

                };
                lstSubject.Add(subject);
            }

            TeacherSubjectViewModel model = new TeacherSubjectViewModel()
            {
                TeacherId = teacher.TeacherId,
                Teacher = teacher,
                Subjects = lstSubject.OrderBy(x => x.SubjectName).ToList()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubjectCreate([Bind(Include = "TeacherId,subjects")] TeacherSubjectViewModel model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            bool successed = false;
            bool exists = false;

            foreach (var subject in model.Subjects)
            {
                if (subject.Status)
                {
                    bool Exists = _db.TeacherSubjects.Any(d => d.SubjectId == subject.SubjectId);
                    if (Exists)
                    {
                        List<TeacherSubject> findteachersubject = _db.TeacherSubjects.Where(d => d.SubjectId == subject.SubjectId).ToList();

                        if (findteachersubject != null)
                        {
                            foreach (var teacherSubject in findteachersubject)
                            {
                                Teacher teacher = _db.Teachers.Find(teacherSubject.TeacherId);
                                if (teacher.EduYearId == GetEduYearId)
                                {
                                    exists = true;
                                }
                            }
                        }
                    }

                    if (!exists)
                    {
                        if (ModelState.IsValid)
                        {
                            TeacherSubject sbmodel = new TeacherSubject()
                            {
                                SubjectId = subject.SubjectId,
                                TeacherId = model.TeacherId,
                            };

                            _db.TeacherSubjects.Add(sbmodel);
                            _db.SaveChanges();
                            successed = true;
                        }
                        else
                        {
                            successed = false;
                        }
                    }
                    exists = false;
                }
            }
            if (successed)
            {
                return Json("");
            }
            else
            {
                return Json("This subject has already been assigned.");
            }
        }

        public ActionResult SubjectDelete(long? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeacherSubject subject = _db.TeacherSubjects.Find(id);
            subject.Subject = _db.Subjects.Find(subject.SubjectId);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

MaspTeachingWebmvc/EduExamine/Views/Teachers/ChapterDisplay.cshtml
@using PagedList;
@using PagedList.Mvc;
@model EduExamine.Models.TeacherChapterViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}
<div class="container-start">
    <div class="row">
        <div class="col-md-12 top_head">
            <a href="@Url.Action("TIndex", "Teachers", null)" class="lnk lnk-default">
                @Model.teacher.FullName
            </a>
            <span class="glyphicon glyphicon-menu-right small"></span>
            <a href="@Url.Action("SubjectDisplay", "Teachers", new { id = Model.teacher.TeacherId })" class="lnk lnk-default">
                @Model.subject.SubjectName
            </a>
            <span class="glyphicon glyphicon-menu-right small"></span>
            Chapters
        </div>
        <div class="col-md-12 top-twenty">
            @if (Model.Chapters.Count() != 0)
            {
                foreach (var item in Model.Chapters)
                {
                    <div class="col-lg-2 newBox" title="@item.ChapterName">
                        <div class="row head">
                            @item.ChapterName
                        </div>
                        <div class="row control">
                            <div class="col-md-12 btntext">
                                @Html.ActionLink("Settings", "SettingsDisplay", new { id = item.ChapterId, subjectid = item.SubjectId, teacherid = Model.teacher.TeacherId  })
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="col-lg-12 newBox" title="No records">
                    <div class="row head" style="height:250px;">
                        No Chapters added to @Model.subject.SubjectName.<br />
                        <br />
                        <p style="font-size:11px;">
                            Go to Class >> Subject >> Chapters to Add chapter.
                        </p>
                    </div>
                    <div class="row control">

                    </div>
                </div>
            }
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Teachers/Create.cshtml
@model EduExamine.Models.Teacher

@{
    ViewBag.Title = "Add New";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}

<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Add @Model.Types</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @using (Ajax.BeginForm("Create", new AjaxOptions { }))
            {
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>

                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.Types)

                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER FULL NAME" } })
                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    @Html.EditorFor(model => model.LoginName, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER LOGIN NAME" } })
                    @Html.ValidationMessageFor(model => model.LoginName, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @placeholder = "PASSWORD", @type = "password" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
                    <input type="password" id="CPassword" name="CPassword" class="form-control" placeholder="CONFIRM PASSWORD" />
                </div>
                <div class="form-group text-right">
                    <input id="submit" type="button" disabled="disabled" value="Save" onclick="submitUniversal(this, '@Url.Action("TIndex", "Teachers", new { menuId = (int)Model.Types })');" class="btn btn-info" />
                    <a href="@Url.Action("TIndex", "Teachers", new { menuId = (int)Model.Types })" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            var errorD = $("div#errorD");
            $("input#CPassword").on("keyup", function () {
                var btnSubmit = $("#submit");
                btnSubmit.attr("disabled", "disabled");
                var cpassword=$(this).val();
                var password = $("input#Password").val();

                if(password == cpassword)
                {
                    errorD.show();
                    errorD.text("Password Matched.")
                    btnSubmit.removeAttr("disabled", "disabled");
                }
                else
                {
                    errorD.show();
                    errorD.text("Password does not Matched.")
                }
            });
        });
    </script>
}

MaspTeachingWebmvc/EduExamine/Views/Teachers/Delete.cshtml
@model EduExamine.Models.Teacher
@{
    ViewBag.Title = "Add New";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}
<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Add @Model.Types</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @using (Ajax.BeginForm("Delete", new AjaxOptions { }))
            {
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">
                    </div>
                </div>
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.Types)
                @Html.HiddenFor(model => model.TeacherId)
                <p>Are you sure want to delete?</p>
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER FULL NAME" } })
                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    @Html.EditorFor(model => model.LoginName, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER LOGIN NAME" } })
                    @Html.ValidationMessageFor(model => model.LoginName, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group text-right">
                    <input id="submit" type="button" value="Delete" onclick="submitUniversal(this, '@Url.Action("TIndex", "Teachers", new { menuId = (int)Model.Types })');" class="btn btn-danger" />
                    <a href="@Url.Action("TIndex", "Teachers", new { menuId = (int)Model.Types })" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Teachers/Edit.cshtml
@model EduExamine.Models.Teacher

@{
    ViewBag.Title = "Add New";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}

<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Add @Model.Types</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @using (Ajax.BeginForm("Edit", new AjaxOptions { }))
            {
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>

                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.Types)
                @Html.HiddenFor(model => model.TeacherId)

                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER FULL NAME" } })
                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    @Html.EditorFor(model => model.LoginName, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER LOGIN NAME" } })
                    @Html.ValidationMessageFor(model => model.LoginName, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @placeholder = "PASSWORD", @type = "password" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
                    <input type="password" id="CPassword" name="CPassword" class="form-control" placeholder="CONFIRM PASSWORD" />
                </div>
                <div class="form-group text-right">
                    <input id="submit" type="button" disabled="disabled" value="Edit" onclick="submitUniversal(this, '@Url.Action("TIndex", "Teachers", new { menuId = (int)Model.Types })');" class="btn btn-success" />
                    <a href="@Url.Action("TIndex", "Teachers", new { menuId = (int)Model.Types })" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            var errorD = $("div#errorD");
            $("input#CPassword").on("keyup", function () {
                var btnSubmit = $("#submit");
                btnSubmit.attr("disabled", "disabled");
                var cpassword = $(this).val();
                var password = $("input#Password").val();

                if (password == cpassword) {
                    errorD.show();
                    errorD.text("Password Matched.")
                    btnSubmit.removeAttr("disabled", "disabled");
                }
                else {
                    errorD.show();
                    errorD.text("Password does not Matched.")
                }
            });
        });
    </script>
}

MaspTeachingWebmvc/EduExamine/Views/Teachers/SubjectCreate.cshtml
@model EduExamine.Models.TeacherSubjectViewModel

@{
    ViewBag.Title = "Add New";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}

<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Add Subject</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @if (Model.Subjects.Count != 0)
            {
                using (Ajax.BeginForm("SubjectCreate", new AjaxOptions { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.TeacherId)
                    <div class="alert-danger error-list">
                        <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                        </div>
                    </div>
                    <div class="col-md-12 bg-info" style="padding:5px; padding-left:10px;">
                        Subjects
                    </div>
                    <div class="col-md-12 subject-lstbox">
                        @for (int i = 0; i < Model.Subjects.Count; i++)
                        {

                        @Html.HiddenFor(d => @Model.Subjects[i].SubjectId)
                        <div class="col-md-12 lstdata">
                            @Html.EditorFor(model => model.Subjects[i].Status) @Model.Subjects[i].SubjectName - <lbl style="font-size:11px;">@Model.Subjects[i].ClassName</lbl>
</div>
                        }
                    </div>
                    <div class="col-md-12 bg-info text-right" style="padding:5px;">
                        <input id="submit" type="button" value="Add" onclick="submitUniversal(this, '@Url.Action("SubjectDisplay", "Teachers", new { id = Model.TeacherId })')" class="btn btn-info" />
                        <a href="@Url.Action("SubjectDisplay", "Teachers", new { id = Model.TeacherId })" class="btn btn-default">
                            Back
                        </a>
                    </div>
                }
            }
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Teachers/SubjectDelete.cshtml
@model EduExamine.Models.TeacherSubject

@{
    ViewBag.Title = "Add New";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}

<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Delete Subject</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @using (Ajax.BeginForm("SubjectDelete", new AjaxOptions { }))
            {
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>

                @Html.AntiForgeryToken()
                @Html.HiddenFor(d => d.TeacherId)
                @Html.HiddenFor(d=> d.TeacherSubjectId)
                <p>Are you sure want to delete?</p>
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-subscript"></i></span>
                    @Html.EditorFor(model => model.Subject.SubjectName, new { htmlAttributes = new { @class = "form-control", } })
                    @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group text-right">
                    <input id="submit" type="button" value="Delete" onclick="submitUniversal(this, '@Url.Action("SubjectDisplay", "Teachers", new { id = Model.TeacherId })')" class="btn btn-danger" />
                    <a href="@Url.Action("SubjectDisplay", "Teachers", new { id = Model.TeacherId })" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Teachers/SubjectDisplay.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<EduExamine.Models.TeacherSubject>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}
<div class="container-start">
    <div class="row">
        <div class="col-md-12 top_head">
            <a href="@Url.Action("TIndex", "Teachers", null)" class="lnk lnk-default">
                @Model.First().Teacher.FullName
            </a>
            <span class="glyphicon glyphicon-menu-right small"></span>
            Subjects
        </div>
        <div class="col-md-12 text-left" title="Add New Subject">
            <h5>
                @Html.ActionLink("+ Add", "SubjectCreate", new { id = @Model.First().Teacher.TeacherId })
            </h5>
        </div>

        <div class="col-md-12">
            @if (Model.First().SubjectId != 0)
            {
                foreach (var item in Model)
                {
                    <div class="col-lg-2 newBox" title="@item.Subject.SubjectName - @item.Subject.Classes.ClassName">
                        <div class="row head">
                            @item.Subject.SubjectName <lbl style="font-size:11px;">@item.Subject.Classes.ClassName</lbl>
                        </div>
                        <div class="row control">
                            @*<div class="col-md-6 btntext" title="Add Subject">
                                @Html.ActionLink("Chapters", "ChapterDisplay", new { id = item.TeacherSubjectId })
                            </div>*@
                            <div class="col-md-12 btntext" title="Remove Subject">
                                @Html.ActionLink("Delete", "SubjectDelete", new { id = item.TeacherSubjectId })
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="col-lg-12 newBox" title="No records">
                    <div class="row head" style="height:250px;">
                        No subjects added to this selected class.<br /><br />
                        <p style="font-size:11px;">
                            Go to Class >> Subjects to Add subject.
                        </p>
                    </div>
                    <div class="row control">

                    </div>
                </div>
            }
        </div>
        <div class="col-md-12 text-center top-twenty">
            @Html.PagedListPager(Model, page => Url.Action("SubjectDisplay", new { page }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Teachers/_HomeMenu.cshtml
@using EduExamine.Models;
@model IEnumerable<EduExamine.Models.Teacher>

@functions{
    public string classResult(TeacherType adminType, TeacherType menuId)
    {
        return Model.First().Types.Equals(adminType) && Model.First().Types.Equals(menuId) ? "col-md-12 onHoverActive" : "col-md-12 onHover";
    }
}

@*<div class="@classResult(Model.First().Types,TeacherType.Principal)" title="Select Principal Tab">
    <a class="text-center" href="@Url.Action("TIndex", new { menuid = 0})">
        <h5>Principal</h5>
    </a>
</div>*@
@*<div class="@classResult(Model.First().Types,TeacherType.Teacher)" title="Select Teacher Tab">
    <a class="text-center">
        <h5>Teacher</h5>
    </a>
</div>*@

@section scripts
{
    <script>
        $(document).ready(function () {
            $('a.text-center').click(function () {
                alert($(this).closest('div'));
                console.log($(this).closest('div').parent().class());
            });
        });
    </script>
}