MaspTeachingWebmvc/EduExamine/Controllers/EduYearsController.cs
using EduExamine.Models;
using PagedList;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EduExamine.Controllers
{
    public class EduYearsController : Controller
    {
        EduExamineContext _db;
        public HttpCookie userCookie;
        public AdminType adminType;

        public EduYearsController()
        {
            _db = new EduExamineContext();
        }
        public bool LoginStatus()
        {
            if (Request.Cookies["MapsUser"] != null)
            {
                userCookie = HttpContext.Request.Cookies["MapsUser"];
                adminType = (AdminType)Enum.Parse(typeof(AdminType), userCookie["Type"], true);
                return true;
            }
            return false;
        }


        public ActionResult EdIndex(int? page, string Search = null)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (!adminType.Equals(AdminType.Admin))
                return RedirectToAction("Index", "SubAdmin", null);

            if (Search != null)
            {
                var model = _db.EduYears.Where(d => d.EduYearName.Contains(Search)).OrderByDescending(o => o.EduYearName).ToList();
                return View(model.ToPagedList(page ?? 1, 10));
            }
            else
            {
                var model = _db.EduYears.OrderByDescending(o => o.EduYearName).ToList();
                return View(model.ToPagedList(page ?? 1, 10));
            }
        }


        public ActionResult Create()
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (!adminType.Equals(AdminType.Admin))
                return RedirectToAction("Index", "SubAdmin", null);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EduYearName,EduStart,EduEnd")] EduYear model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);
            if (model.EduStart >= model.EduEnd)
                return Json("start date should be before end date");

            bool Exists = _db.EduYears.Any(d => d.EduYearName.Equals(model.EduYearName));
            if (!Exists)
            {
                if (ModelState.IsValid)
                {
                    _db.EduYears.Add(model);
                    _db.SaveChanges();
                    return Json("");
                }
                else
                {
                    return Json("Model is not valid.");
                }
            }
            else
            {
                return Json("Try another label name");
            }
        }

        public ActionResult Edit(int? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (!adminType.Equals(AdminType.Admin))
                return RedirectToAction("Index", "SubAdmin", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EduYear eduYear = _db.EduYears.Find(id);
            if (eduYear == null)
            {
                return HttpNotFound();
            }
            return View(eduYear);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EduYearId,EduYearName,EduStart,EduEnd")] EduYear model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);
            if (model.EduStart >= model.EduEnd)
                return Json("start date should be before end date");

            bool Exists = _db.EduYears.Any(d => d.EduYearName.Equals(model.EduYearName));
            if (!Exists)
            {
                if (ModelState.IsValid)
                {
                    _db.Entry(model).State = EntityState.Modified;
                    _db.SaveChanges();
                    return Json("");
                }
                else
                {
                    return Json("Model is not valid.");
                }
            }
            else
            {
                return Json("Try another label name");
            }
        }

        public ActionResult Delete(int? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (!adminType.Equals(AdminType.Admin))
                return RedirectToAction("Index", "SubAdmin", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EduYear eduYear = _db.EduYears.Find(id);
            if (eduYear == null)
            {
                return HttpNotFound();
            }
            return View(eduYear);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            EduYear eduYear = _db.EduYears.Find(id);
            _db.EduYears.Remove(eduYear);
            _db.SaveChanges();
            return Json("");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MaspTeachingWebmvc/EduExamine/Controllers/ExamsController.cs
using EduExamine.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EduExamine.Controllers
{
    public class ExamsController : Controller
    {
        EduExamineContext _db;
        public HttpCookie userCookie;
        public AdminType AdminType;
        public int? GetEduYearId;

        public ExamsController()
        {
            _db = new EduExamineContext();
        }


        public bool LoginStatus()
        {
            if (Request.Cookies["MapsUser"] != null)
            {
                userCookie = HttpContext.Request.Cookies["MapsUser"];
                AdminType = (AdminType)Enum.Parse(typeof(AdminType), userCookie["Type"], true);
                GetEduYearId = Convert.ToInt32(userCookie["EduYearId"]);
                return true;
            }
            return false;
        }


        public ActionResult EIndex(int? page, string search = null)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (search != null)
            {
                var model = _db.Exams.Where(d => d.EduYearId == GetEduYearId && d.ExamName.Contains(search)).OrderBy(d => d.ExamId).ToList();
                return View(model.ToPagedList(page ?? 1, 10));
            }
            var exams = _db.Exams.Where(d => d.EduYearId == GetEduYearId).OrderBy(d => d.ExamId).ToList();
            return View(exams.ToPagedList(page ?? 1, 10));
        }

        public ActionResult Create()
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ExamId,ExamName,EduYearId")] Exam model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            bool Exists = _db.Exams.Any(d => d.ExamName.Equals(model.ExamName));
            if (!Exists)
            {
                if (ModelState.IsValid)
                {
                    model.EduYear = _db.EduYears.Find((int)GetEduYearId);
                    model.EduYearId = (int)GetEduYearId;
                    _db.Exams.Add(model);
                    _db.SaveChanges();
                    return Json("");
                }
                else
                {
                    return Json("Model is not valid.");
                }
            }
            else
            {
                return Json("Try another label name");
            }
        }

        public ActionResult Edit(long? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exam exam = _db.Exams.Find(id);
            if (exam == null)
            {
                return HttpNotFound();
            }
            ViewBag.EduYearId = new SelectList(_db.EduYears, "EduYearId", "EduYearName", exam.EduYearId);
            return View(exam);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ExamId,ExamName,EduYearId")] Exam model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (ModelState.IsValid)
            {
                model.EduYear = _db.EduYears.Find(model.EduYearId);
                model.EduYearId = model.EduYearId;
                _db.Entry(model).State = EntityState.Modified;
                _db.SaveChanges();
                return Json("");
            }
            else
            {
                return Json("Model is not valid.");
            }
        }

        public ActionResult Delete(long? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exam exam = _db.Exams.Find(id);
            if (exam == null)
            {
                return HttpNotFound();
            }
            return View(exam);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed([Bind(Include = "ExamId")] Exam model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            Exam exam = _db.Exams.Find(model.ExamId);
            _db.Exams.Remove(exam);
            _db.SaveChanges();
            return Json("");
        }

        public ActionResult ClassDisplay(int? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            ExamsClassViewModel model = new ExamsClassViewModel()
            {
                Exam = _db.Exams.Find(id),
                Classess = _db.Classess.OrderBy(d => d.ClassesId).ToList()
            };


            return View(model);
        }

        public ActionResult SubjectDisplay(long? id, long? examid)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            ExamsClassesSubjectViewModel model = new ExamsClassesSubjectViewModel()
            {
                Exam = _db.Exams.Find(examid),
                Classess = _db.Classess.Find(id),
                examSubjects = new List<ExamSubject>()
            };

            List<ExamSubject> examSubjects = _db.ExamSubjects.Where(d => d.ExamId == examid).ToList();

            List<Subject> subjectList = _db.Subjects.Where(d => d.ClassesId == id).ToList();

            int totalpercentage, totalavgmarks, totalmarks;
            totalpercentage = totalavgmarks = totalmarks = 0;

            foreach (var subject in subjectList)
            {
                ExamSubject findVal = examSubjects.Where(d => d.SubjectId == subject.SubjectId && d.ExamId == examid).FirstOrDefault();

                ExamSubject addModel = new ExamSubject()
                {
                    AvgMarks = findVal != null ? findVal.AvgMarks : 0,
                    Exam = model.Exam,
                    ExamId = (long)examid,
                    ExamMarks = findVal != null ? findVal.ExamMarks : 0,
                    ExamSubjectId = findVal != null ? findVal.ExamSubjectId : 0,
                    Percentages = findVal != null ? findVal.Percentages : 0,
                    Subject = subject,
                    SubjectId = subject.SubjectId
                };

                totalavgmarks += addModel.AvgMarks;
                totalmarks += addModel.ExamMarks;

                model.examSubjects.Add(addModel);
            }
            if (totalavgmarks != 0 && totalmarks != 0)
            {
                totalpercentage = ((totalavgmarks * 100) / totalmarks);
            }
            model.TotalAvg = totalavgmarks;
            model.TotalMarks = totalmarks;
            model.TotalPercentage = totalpercentage;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitExamSubjectMarks([Bind(Include = "examSubjects")] ExamsClassesSubjectViewModel model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (ModelState.IsValid)
            {
                if (model.examSubjects != null)
                {
                    foreach (var item in model.examSubjects)
                    {
                        Exam exam = _db.Exams.Find(item.ExamId);
                        Subject subject = _db.Subjects.Find(item.SubjectId);

                        bool Exists = _db.ExamSubjects.Any(d => d.ExamId == item.ExamId && d.ExamSubjectId == item.ExamSubjectId);

                        ExamSubject addModel = new ExamSubject()
                        {
                            AvgMarks = item.AvgMarks,
                            ExamMarks = item.ExamMarks,
                            ExamSubjectId = item.ExamSubjectId,
                            Percentages = item.Percentages,
                            Exam = exam,
                            ExamId = item.ExamId,
                            Subject = subject,
                            SubjectId = item.SubjectId
                        };

                        if (addModel.AvgMarks <= addModel.ExamMarks)
                        {
                            if (!Exists)
                            {
                                _db.ExamSubjects.Add(addModel);
                            }
                            else
                            {
                                _db.Entry(addModel).State = EntityState.Modified;
                            }
                        }
                        else
                        {
                            return Json("Error: cause of some wrong information feeded.");
                        }
                        _db.SaveChanges();
                    }
                    return Json("");
                }
                else
                {
                    return Json("Model is not valid.");
                }
            }
            else
            {
                return Json("Model is not valid.");
            }

        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MaspTeachingWebmvc/EduExamine/Views/Shared/Adminmenu.cshtml
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand" title="@Request.Cookies["MapsUser"]["Email"].ToString()">
                <a href="@Url.Action("AdIndex","Admins",null)" class="circle">
                    <span>@Request.Cookies["MapsUser"]["Type"].ToString().Substring(0, 1)</span>
                </a>
            </div>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="@Url.Action("AdIndexAdmin", "Admins", null)">ADMIN</a></li>
                <li><a href="@Url.Action("EdIndex", "EduYears", null)">EDU-YEAR</a></li>
                <li><a href="@Url.Action("TTIndex", "TeachingTypes", null)">TtYPE</a></li>
                <li><a href="@Url.Action("CIndex", "Classes", null)">CLASS</a></li>
                <li><a href="@Url.Action("TIndex", "Teachers", null)">TEACHER</a></li>
                <li><a href="@Url.Action("EIndex", "Exams", null)">EXAM</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" title="LOGOUT">
                <li><a>@Request.Cookies["MapsUser"]["FromYear"].ToString()</a></li>
                <li><a href="@Url.Action("Logout","Admins",null)">LOGOUT</a></li>
            </ul>
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Shared/SubAdminMenu.cshtml
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand" title="@Request.Cookies["MapsUser"]["Email"].ToString()">
                <a href="@Url.Action("AdIndex","Admins",null)" class="circle">
                    <span>@Request.Cookies["MapsUser"]["Type"].ToString().Substring(0, 1)</span>
                </a>
            </div>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="@Url.Action("AdIndexAdmin", "Admins", null)">ADMIN</a></li>
                <li><a href="@Url.Action("EdIndex", "EduYears", null)">EDU-YEAR</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" title="LOGOUT">
                <li><a>@Request.Cookies["MapsUser"]["FromYear"].ToString()</a></li>
                <li><a href="@Url.Action("Logout","Admins",null)">LOGOUT</a></li>
            </ul>
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin - @ViewBag.Title</title>
    <link rel="shortcut icon" href="~/lOGO.ico">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderSection("Adminmenu", required: false)
    <div class="my-body">
        <div class="container" style="margin-bottom:30px;">
            @RenderBody()
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MaspTeachingWebmvc/EduExamine/Views/Shared/_EmptyView.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MAPS", "Login", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>
    <div class="my-body">
        <div class="container">
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MaspTeachingWebmvc/EduExamine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Maps Edu", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Year", "Index", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Login", "Login", "Admins")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Devendra Gohel +91-9909980330</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MaspTeachingWebmvc/EduExamine/Views/Shared/_SubAdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin - @ViewBag.Title</title>
    <link rel="shortcut icon" href="~/lOGO.ico">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderSection("SubAdminMenu", required: false)
    <div class="my-body">
        <div class="container" style="margin-bottom:30px;">
            @RenderBody()
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>