MaspTeachingWebmvc/EduExamine/Controllers/TeachingTypesController.cs
using EduExamine.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EduExamine.Controllers
{
    public class TeachingTypesController : Controller
    {
        private EduExamineContext _db;
        public HttpCookie userCookie;
        public AdminType AdminType;

        public TeachingTypesController()
        {
            _db = new EduExamineContext();
        }

        public bool LoginStatus()
        {
            if (Request.Cookies["MapsUser"] != null)
            {
                userCookie = HttpContext.Request.Cookies["MapsUser"];
                AdminType = (AdminType)Enum.Parse(typeof(AdminType), userCookie["Type"], true);
                return true;
            }
            return false;
        }

        public ActionResult TTIndex()
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            return View(_db.TeachingTypes.ToList());
        }


        public ActionResult Create()
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);
            TeachingType model = new TeachingType() { Name = "", OrderId = (_db.TeachingTypes.Count() + 1) };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,OrderId")] TeachingType model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            bool Exists = _db.TeachingTypes.Any(d => d.Name.Equals(model.Name));
            if (!Exists)
            {
                if (ModelState.IsValid)
                {
                    _db.TeachingTypes.Add(model);
                    _db.SaveChanges();
                    return Json("");
                }
                else
                {
                    return Json("Model is not valid.");
                }
            }
            else
            {
                return Json("Try another label name");
            }
        }

        public ActionResult Edit(int? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeachingType teachType = _db.TeachingTypes.Find(id);
            if (teachType == null)
            {
                return HttpNotFound();
            }
            return View(teachType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TeachingTypeId,Name,OrderId")] TeachingType model)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            bool Exists = _db.TeachingTypes.Any(d => d.Name.Equals(model.Name));
            if (!Exists)
            {
                if (ModelState.IsValid)
                {
                    _db.Entry(model).State = EntityState.Modified;
                    _db.SaveChanges();
                    return Json("");
                }
                else
                {
                    return Json("Model is not valid.");
                }
            }
            else
            {
                return Json("Try another label name");
            }
        }

        public ActionResult Delete(int? id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeachingType teachingType = _db.TeachingTypes.Find(id);
            if (teachingType == null)
            {
                return HttpNotFound();
            }
            return View(teachingType);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!LoginStatus())
                return RedirectToAction("Login", "Admins", null);

            TeachingType teachingType = _db.TeachingTypes.Find(id);
            _db.TeachingTypes.Remove(teachingType);
            _db.SaveChanges();
            return Json("");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MaspTeachingWebmvc/EduExamine/Views/TeachingTypes/Create.cshtml
@model EduExamine.Models.TeachingType

@{
    ViewBag.Title = "Add New";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}

<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Add Teaching Type</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @using (Ajax.BeginForm("Create", new AjaxOptions { }))
            {
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>

                @Html.AntiForgeryToken()
                @Html.HiddenFor(d => d.OrderId)
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-sort-by-order"></i></span>
                    @Html.EditorFor(model => model.OrderId, new { htmlAttributes = new { @disabled="disabled", @class = "form-control", @placeholder = "ORDER ID" } })
                    @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER NAME OF TEACHING TYPE" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group text-right">
                    <input id="submit" type="button" value="Save" onclick="submitUniversal(this, '@Url.Action("TTIndex", "TeachingTypes", null)')" class="btn btn-info" />
                    <a href="@Url.Action("TTIndex", "TeachingTypes", null)" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/TeachingTypes/Delete.cshtml
@model EduExamine.Models.TeachingType

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}

<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Delete Teaching Type</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @using (Ajax.BeginForm("Delete", new AjaxOptions { }))
            {
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>

                @Html.AntiForgeryToken()
                @Html.HiddenFor(d => d.TeachingTypeId)
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-sort-by-order"></i></span>
                    @Html.EditorFor(model => model.OrderId, new { htmlAttributes = new { @class = "form-control", @placeholder = "ORDER ID" } })
                    @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER NAME OF TEACHING TYPE" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group text-right">
                    <input id="submit" type="button" value="Delete" onclick="submitUniversal(this, '@Url.Action("TTIndex", "TeachingTypes", null)')" class="btn btn-danger" />
                    <a href="@Url.Action("TTIndex", "TeachingTypes", null)" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/TeachingTypes/Edit.cshtml
@model EduExamine.Models.TeachingType

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}

<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <h4 style="font-weight:normal; font-family:'Century Gothic';">Edit Teaching Type</h4>
        </div>
        <div class="col-md-12 top-twenty">
            @using (Ajax.BeginForm("Edit", new AjaxOptions { }))
            {
                <div class="alert-danger error-list">
                    <div id="errorD" style="padding:10px; margin-bottom:20px; display:none;">

                    </div>
                </div>

                @Html.AntiForgeryToken()
                @Html.HiddenFor(d => d.TeachingTypeId)
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-sort-by-order"></i></span>
                    @Html.EditorFor(model => model.OrderId, new { htmlAttributes = new { @class = "form-control", @placeholder = "ORDER ID" } })
                    @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group input-group input-group-lg">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "ENTER NAME OF TEACHING TYPE" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger form-control-feedback" })
                </div>
                <div class="form-group text-right">
                    <input id="submit" type="button" value="Edit" onclick="submitUniversal(this, '@Url.Action("TTIndex", "TeachingTypes", null)')" class="btn btn-success" />
                    <a href="@Url.Action("TTIndex", "TeachingTypes", null)" class="btn btn-default">
                        Back
                    </a>
                </div>
            }
        </div>
    </div>
</div>

MaspTeachingWebmvc/EduExamine/Views/TeachingTypes/TTIndex.cshtml
@model IEnumerable<EduExamine.Models.TeachingType>

@{
    ViewBag.Title = "LIndex";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Adminmenu
{
    @Html.Partial("~/Views/Shared/Adminmenu.cshtml")
}
<div class="container-start">
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Serial No.
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().Name)
                        </th>
                        <th>
                            @Html.ActionLink("+ Add", "Create")
                        </th>
                    </tr>
                </thead>
                <tbody id="searchResult">
                    @foreach (var item in Model)
                    {
                        <tr style="padding:5px; background-color:#F1F1F1; border-bottom: solid 1px #d1d1d1;">
                            <td>
                                @Html.DisplayFor(modelItem => item.OrderId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.TeachingTypeId }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.TeachingTypeId })
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>